name: Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release Version(canary, pre, latest)'
        required: true
        default: 'canary'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 14.x
        uses: actions/setup-node@main
        with:
          node-version: 14.x

      - name: Init
        run: npm install -g pnpm && pnpm run setup

      - name: Prepare
        run: pnpm run prepare --filter ./packages

      - name: Bump Canary Version
        if: ${{  github.event.inputs.release-version == 'canary' }}
        run: pnpm run bump -- --snapshot canary && pnpm run release -- --tag canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Bump Pre Versin
        if: ${{  github.event.inputs.release-version == 'pre' }}
        run: pnpm run release -- --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Latest Version
        if: ${{  github.event.inputs.release-version == 'latest' }}
        run: pnpm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
